options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/unified-mender-447706-v0/my-repo/sinatra-app', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/unified-mender-447706-v0/my-repo/sinatra-app']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'sinatra-app'
    - '--image'
    - 'asia-south1-docker.pkg.dev/unified-mender-447706-v0/my-repo/sinatra-app'
    - '--platform'
    - 'managed'
    - '--region'
    - 'asia-south1'
    - '--allow-unauthenticated'
